### PR TITLE
Feature/42 mapping sofa score

### PR DESCRIPTION
**Pull request by jsachau**
Finished the sofa score mapping.

### CODE REVIEW

**Comment by ppazos** [comment]
@jsachau please merge with develop to resolve conflicts

**Comment by jsachau** [comment]
I have merged the newest develop branch.

**Comment by ppazos** [comment]
@jsachau please fix the failing tests, check CI https://circleci.com/gh/ehrbase/fhir-bridge/133?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jsachau** [comment]
I have fixed the tests.

**Review by ppazos — APPROVED** [review]
Looks good :shipit:

**Pull request merged**
