### PR TITLE
Feature/70 mapping smoking status

### PR DESCRIPTION
**Pull request by MDSchulze**
Fixes ehrbase/num_platform/issues/70

### CODE REVIEW

**Comment by ppazos** [comment]
@MDSchulze can you please check the conflicts with develop branch and update the tests that are not passing?

**Comment by birgerhaarbrandt** [comment]
@ppazos please re-review with high priority, we need this by tomorrow

**Comment by ppazos** [comment]
@birgerhaarbrandt this can be reviewed after the conflicts are solved. Not sure if @MDSchulze or @SevKohler are working on this one.

**Review by ppazos — APPROVED** [review]
conflicts solved, tests passing

**Pull request merged**
