### PR TITLE
Feature/104 diagnose mapping

### PR DESCRIPTION
**Pull request by jsachau**
The class `DiagnoseCompositionConverter` is still part of the project as I was uncertain if I could remove it without causing damage in other tests. @ppazos Can you remove/replace the old diagnosis (DefaultCondition) if necessary?

### CODE REVIEW

**Comment by jsachau** [comment]
The template needs an update so that the remains test passes. I currently wait for Antje to send me an update.

**Comment by jsachau** [comment]
We noticed a problem in the openEHR_SDK project. Once the [issue](https://github.com/ehrbase/openEHR_SDK/issues/171) is fixed we need to update the opt class structure again.

**Comment by ppazos** [comment]
@jsachau do the new condition profiles override the old condition? If so, can you create an issue for me? I'll take it ASAP. Thanks.

**Comment by jsachau** [comment]
@ppazos: I created the diagnose mapping. A description can be found [here](https://github.com/ehrbase/fhir-bridge/pull/159). The class `DiagnoseCompositionConverter` is still part of the project as I was uncertain if I could remove it without causing damage in other tests. Please remove/replace the old diagnosis (DefaultCondition). Be aware that the default condition is used in several tests as a dummy entry.

**Comment by SevKohler** [comment]
Please add the new tests, and update the mapping.

**Comment by jsachau** [comment]
@SevKohler what do you mean with "new tests" and the "mapping update"? @ppazos Do you have any updates on the removal?

**Comment by ppazos** [comment]
@jsachau sorry, I'm working on other issues raised on the FHIR bridge repo. In general you can remove things if you know those are legacy and superseded by new ones, because you can run the tests after and check any issues caused by removing profiles or mappings. What I don't manage is it knowledge of which profiles or mappings are obsolete in preference of new ones. I guess the num team knows more about that. Can you try to remove it and run the tests?

**Comment by SevKohler** [comment]
Error is thrown at line 107 in the GeccoDiagnoseCompositionConverter for the dependence on ventilator. Category is nevertheless present in the create file. This relates to the failing tests not to the problem about the template which i hope is fixed soon

**Comment by SevKohler** [comment]
I added the snomed code manually, since its not included in the autogenerated files, yet (stefan hopefully fixes that). Nevertheless in the end it does not matter for now if its added manually or automatically. Tests should now all run accordingly. Is the template problem still of relevance @jsachau. if not i would suggest you write the new tests so this thing can be finally merged. 

I would suggest changing the code again when the bug is fixed.

**Comment by SevKohler** [comment]
blocked openEHR_SDK[#171](https://github.com/ehrbase/openEHR_SDK/issues/171)

**Pull request merged**
