### PR TITLE
Apply Google Java Style Guide

### PR DESCRIPTION
**Pull request by wlad**
This PR does an initial reformat of the whole code base following [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) and solves the following issues

- resolves https://github.com/ehrbase/project_management/issues/440
- resolves https://github.com/ehrbase/project_management/issues/441

It adds a step to CI pipeline which breaks the build if formatting does not comply with [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html). More over it adds a maven plugin that deploys a pre-commit git hook (on each developers machine) that will auto-format code (following Google Java Style) before each commit.

The solution is based on 
- https://github.com/Cosium/git-code-format-maven-plugin
- https://github.com/google/google-java-format

Documentation was added to this [project's wiki](https://github.com/ehrbase/fhir-bridge/wiki/Coding-Standard)

### CODE REVIEW

**Comment by ppazos** [comment]
@wlad was this PR reviewed?

**Comment by SevKohler** [comment]
@wlad Whats with this PR ?

**Comment by wlad** [comment]
@SevKohler this one is outdated. It has to be repeated from scratch to get something useful from it. Let's keep it in WIP status so that I know what needs to be done when we decide to try it again.

**Comment by subigre** [comment]
@wlad 
I just rebased your branch with last develop. I thing that the only step that is missing now is to reformat the entire codebase using the maven plugin that you have included.

PS: I have also updated the checkstyle configuration file from `ehrbase_checks.xml` to `google_checks.xml`

**Pull request closed without merging**
