### PR TITLE
NUM-207: Add steps for tagging and publishing the Docker image

### PR DESCRIPTION
**Pull request by af-rsa**
Add local maven to code (you could remove the step where maven is installed), and added jobs for tagging the commits and building and pushing the docker image to DockerHub.

### CODE REVIEW

**Review by StefanWinterfeldtVitasystems — COMMENTED** [review]
Could the Maven Wrapper also be downloaded and installed as part of the pipeline? Then we would not have to include it in the repo.

**Comment by af-rsa** [comment]
> Could the Maven Wrapper also be downloaded and installed as part of the pipeline? Then we would not have to include it in the repo.

It could be, and Wlad had it done it so, but I'd prefer to use wrapper for following reasons:

1) it is added by default by actuator
2) With it you don't need to install maven locally, and all the devs can ensure that they use the same maven version
3) You don't need to separately download maven or use maven docker image in the pipeline.

**Review by StefanWinterfeldtVitasystems — APPROVED** [review]

**Review by wlad — APPROVED** [review]
Looks good overall. @af-rsa please check if you want to update something based on my comments

**Comment by wlad** [comment]
@af-rsa consider using image `cimg/openjdk:11.0.8`
image

**Pull request merged**
