### PR TITLE
CI pipeline w/ Jacoco code coverage, sonarcloud.io and testcontainers integration

### PR DESCRIPTION
**Pull request by wlad**
- implements CI pipeline w/ CircleCI which triggers a build on every commit on any branch
- demonstrates  [testcontainers ](https://www.testcontainers.org/) using Docker Compose Module w/ Junit5 (something that is not yet documented at testcontainers.org)
- uses testcontainers(.org) to start ehrbase & postgresql containers during mvn verify phase (required to successfully run integration tests)
- uses special ehrbaseorg/ehrbase:test_0.13.0 docker image (w/o authentification)
- uses ~~`develop-SNAPSHOT`~~ `v0.3.7` as version for SDK dependency (builds SDK artifacts on jitpack.io based on git tag v0.3.7)

## related issue

closes https://github.com/ehrbase/project_management/issues/334

### CODE REVIEW

**Comment by wlad** [comment]
github displays bs once again

image

actual
image

closing this one to reopen a new PR 🙄

**Comment by wlad** [comment]
oh no, seems everything is correct
image

the ❌  icon left from commit hash displays combined result (ci passed & sonar failed == failed) 

the failed code analysis check can be ignored, is just about duplicate lines 🙄

**Comment by wlad** [comment]
reopen

**Comment by wlad** [comment]
@ppazos / @jakesmolka I've updated SDK to a "static" version. Please review and let me know when I can merge or merge it youself 😉

**Review by jakesmolka — APPROVED** [review]
Looks good!

Except the docker image thing, which is a separate issue now: https://github.com/ehrbase/project_management/issues/342

And the sonar analysis :x: is really unfortunate. Every following build will look like we broke something. Meaningful :x:s will not be that visible due to that. So I propose we either make that quality gate pass asap or alter the rule.

**Comment by wlad** [comment]
@jakesmolka I've created a new QG (quality gate) `EHRbase I` where I raised **Duplicated Lines (%)** to 20%. I set this QG as default for all EHRbase projects

Docker image issue is on my todo.

**Pull request merged**
